web/router.ex
defmodule FacebookClone.Router do
  use FacebookClone.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :require_authenticated do
    plug :authenticate_logged_in
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FacebookClone do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  scope "/", FacebookClone do
    pipe_through [:browser, :require_authenticated]

    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      resources "/photos", PhotoController, except: [:show]
    end

    resources "/friendship_invitations", FriendshipInvitationController,
      only: [:create, :update]
    resources "/friendships/", FriendshipController, only: [:delete]
    get "/friends", FriendshipController, :index

    resources "/posts", PostController, except: [:show]
    resources "/likes", LikeController, only: [:create, :delete]

    resources "/conversations", ConversationController, only: [:index, :show, :create] do
      resources "/messages", MessageController, only: [:new, :create, :delete]
    end

    resources "/groups", GroupController
    resources "/group_users", GroupUserController, only: [:create, :delete]
    delete "/groups/:id/delete_posts", GroupController, :delete_posts

    put "/invitations/:id/accept", EventInvitationController, :update

    resources "/events", EventController do
      resources "/invitations", EventInvitationController,
        only: [:create], as: :invitation

    end
  end

  defp authenticate_logged_in(conn, _) do
    case get_session(conn, :current_user_id) do
      nil ->
        conn
        |> put_flash(:info, "You have to sign in first")
        |> redirect(to: FacebookClone.Router.Helpers.session_path(conn, :new))
        |> halt
      _ ->
        conn
    end
  end

  defp assign_current_user(conn, _) do
    user_id = get_session(conn, :current_user_id)

    conn
    |> assign(:current_user_id, user_id)
    |> assign(:current_user, FacebookClone.UserController.get_by_id(user_id))
  end

  # Other scopes may use custom stacks.
  # scope "/api", FacebookClone do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule FacebookClone.LayoutView do
  use FacebookClone.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= tag :meta, name: "channel_token", content:
        Phoenix.Token.sign(@conn, "user", @conn.assigns.current_user_id) %>

    <title>Facebook Clone</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
  </head>

  <body>
    <div id="app" role="main">
      <header class="app-header">
        <ul class="nav nav-pills pull-right">
          <%= if logged_in?(@conn) do %>
            <li>
              <%= link "Edit profile", to: user_path(@conn, :edit, current_user(@conn)) %>
            </li>
            <li>
              <%= link "Logout", to: session_path(@conn, :delete), method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link "Register", to: registration_path(@conn, :new) %>
            </li>
            <li>
              <%= link "Login", to: session_path(@conn, :new) %>
            </li>
          <% end %>
        </ul>
        <h1>Facebook Clone</h1>
      </div>

      <div id="content-area">
        <section class="sidebar">
          <ul>
            <li>
              <%= link "Posts", to: post_path(@conn, :index) %>
            </li>
            <li>
              <%= link "Messages", to: conversation_path(@conn, :index) %>
            </li>
            <li>
              <%= link "Friends", to: friendship_path(@conn, :index) %>
            </li>
            <li>
              <%= link "Users", to: user_path(@conn, :index) %>
            </li>
            <li>
              <%= if @current_user, do: link("Photos", to: user_photo_path(@conn, :index, @current_user)) %>
            </li>
            <li>
              <%= link "Groups", to: group_path(@conn, :index) %>
            </li>
            <li>
              <%= link "Events", to: event_path(@conn, :index) %>
            </li>
          </ul>
        </section>

        <div class="main">
          <div class="container">
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

            <%= render @view_module, @view_template, assigns %>
          </div>

        </div>

      </div>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>